version: '3'

services:

  chatgpt:
    hostname: chatgpt
    image: ghcr.io/n3d1117/chatgpt-telegram-bot:latest
    volumes:
      - .:/app
    env_file:
      - chatgpt.env
    restart: unless-stopped
